In [1]:
import pandas as pd
import numpy as np
import pickle
from itertools import combinations
from sklearn.metrics import jaccard_score

In [2]:
email_cluster = pd.read_pickle('Email/email_cluster_bert.pkl')
email_cluster

,Topic,Count,Name,Representation,Representative_Docs
0,-1,199971,-1_for_to_the_and,"[for, to, the, and, you, of, in, by, this, our]",[DONATE: Paid for by LisaBlunt Rochester for C...
1,0,55358,0_we_to_our_the,"[we, to, our, the, and, in, this, you, of, can]","[We've set a goal to raise $200,000 inthe next..."
2,1,6494,1_abortion_roe_wade_roe wade,"[abortion, roe, wade, roe wade, reproductive, ...","[Peter, With the Supreme Court’s devastating d..."
3,2,3239,2_georgia_stacey_abrams_kemp,"[georgia, stacey, abrams, kemp, stacey abrams,...",[Will you rush a donation right now to help el...
4,3,2704,3_pennsylvania_fetterman_john_pa,"[pennsylvania, fetterman, john, pa, to, derek,...",[John John Fetterman Lieutenant Governor of Pe...
...,...,...,...,...,...
162,161,152,161_great maga king_maga king_great maga_status,"[great maga king, maga king, great maga, statu...","[**_ But, I didn't want to send you _JUST_ an..."
163,162,152,162_elissa_slotkin_gosar for congress_gosar for,"[elissa, slotkin, gosar for congress, gosar fo...",[** PAID FOR BY GOSAR FOR CONGRESS------------...
164,163,151,163_king_dr_luther_dr king,"[king, dr, luther, dr king, luther king, marti...",[“Life’s most persistent and urgent question i...
165,164,150,164_can click here_you can click_can click_if ...,"[can click here, you can click, can click, if ...",[We rely on grassrootssupporters like you to f...
166,165,149,165_clerkship_court_supreme court_supreme,"[clerkship, court, supreme court, supreme, wil...","[After his second clerkship, hejoined the Wash..."

In [3]:
podcast_cluster = pd.read_pickle('Podcast/podcast-bert-clust.pkl')
podcast_cluster

,Topic,Count,Name,Representation,Representative_Docs
0,-1,165807,-1_the_to_and_you,"[the, to, and, you, of, that, in, is, it, for]",[My friend had his home stolen. The crime is h...
1,0,332665,0_the_and_to_that,"[the, and, to, that, you, of, is, in, it, this]","[And understand, as I said, that these issues ..."
2,1,35191,1_ukraine_russia_putin_the,"[ukraine, russia, putin, the, to, and, of, tha...","[As we'll get to in a second, the economy is o..."
3,2,19568,2_covid_vaccine_the_that,"[covid, vaccine, the, that, and, to, of, it, y...","[I always tell you I'm not a doctor. And, you ..."
4,3,17348,3_abortion_the_that_to,"[abortion, the, that, to, roe, is, of, and, in...","[Uh, the Democrat party has gotten so extreme ..."
...,...,...,...,...,...
133,132,138,132_kanye_kanye west_west_he,"[kanye, kanye west, west, he, like, his, hes, ...","[It's like it's more in the, you know, I'm goi..."
134,133,137,133_no more_has arrived_arrived_cancel culture,"[no more, has arrived, arrived, cancel culture...",[Getter has arrived. The new social media taki...
135,134,136,134_goldmines_an upgrade comedy_upgrade comedy...,"[goldmines, an upgrade comedy, upgrade comedy,...",[I'm back people and I'm coming at you with an...
136,135,129,135_mattress_helix_helixsleepcom_helixsleepcom...,"[mattress, helix, helixsleepcom, helixsleepcom...",[They'll pick it up for you if you don't love ...
137,136,126,136_puretalkcom_promo code_promo_code,"[puretalkcom, promo code, promo, code, month, ...",[You can switch right now at puretalk.com in a...

In [4]:
tv_clusters = pd.read_pickle('/scratch/rm1667/rm1667-outputs/TV/tv-bert-clust.pkl')
tv_clusters

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1910662,-1_the_and_to_of,"[the, and, to, of, you, in, that, is, it, for,...",[\xe2\x99\xaa no once-daily copd medicine... h...
1,0,412553,0_ukraine_russian_russia_putin,"[ukraine, russian, russia, putin, ukrainian, t...",[we\'re going to begin with the very latest on...
2,1,284291,1_xe2x80x94_it_is_we,"[xe2x80x94, it, is, we, you, that, prime, have...","[speaking outside downing street, liz truss sa..."
3,2,89451,2_democrats_biden_republicans_republican,"[democrats, biden, republicans, republican, se...",[although president biden says that he is goin...
4,3,76314,3_covid_vaccine_vaccinated_mask,"[covid, vaccine, vaccinated, mask, we, are, th...","[no, and whatever the reason, as you say, ther..."
...,...,...,...,...,...
314,313,524,313_masters_11_just saw something_year for like,"[masters, 11, just saw something, year for lik...","[(children giggling) hey, i was, uh, thinking ..."
315,314,523,314_snooker_ronnie_world snooker_osullivan,"[snooker, ronnie, world snooker, osullivan, fr...","[at the world snooker championship, ronnie o\x..."
316,315,517,315_niagen_tru niagen_tru_nad,"[niagen, tru niagen, tru, nad, of the root, ca...",[[\xe2\x99\xaa] did you know you can address o...
317,316,512,316_make the most_the most of_make the_million...,"[make the most, the most of, make the, million...","[we\'ve been coming here, since 1868. my grand..."
318,317,506,317_kisqali_metastatic_metastatic breast_metas...,"[kisqali, metastatic, metastatic breast, metas...",[to be a thriver with metastatic breast cancer...

In [5]:
email_words = email_cluster[['Name', 'Representation']].T.drop(columns=[0]).T

In [6]:
podcast_words = podcast_cluster[['Name', 'Representation']].T.drop(columns=[0]).T

In [7]:
tv_words = tv_clusters[['Name', 'Representation']].T.drop(columns=[0]).T

In [8]:
import pandas as pd
from itertools import product

def calculate_jaccard_similarity(email_words, podcast_words, tv_words):
    result = []
    
    # Internal Comparison within Email Words DataFrame
    for idx1, idx2 in product(email_words.index, repeat=2):
        if idx1 != idx2:
            topic1_words = set(email_words.loc[idx1, 'Representation'])
            topic2_words = set(email_words.loc[idx2, 'Representation'])
            jaccard_score = len(topic1_words.intersection(topic2_words)) / len(topic1_words.union(topic2_words))
            result.append({'Source1': 'Email', 'Topic1': idx1-1, 'Source2': 'Email', 'Topic2': idx2-1, 'Similarity': jaccard_score})

    # Internal Comparison within Podcast Words DataFrame
    for idx1, idx2 in product(podcast_words.index, repeat=2):
        if idx1 != idx2:
            topic1_words = set(podcast_words.loc[idx1, 'Representation'])
            topic2_words = set(podcast_words.loc[idx2, 'Representation'])
            jaccard_score = len(topic1_words.intersection(topic2_words)) / len(topic1_words.union(topic2_words))
            result.append({'Source1': 'Podcast', 'Topic1': idx1-1, 'Source2': 'Podcast', 'Topic2': idx2-1, 'Similarity': jaccard_score})

    # Internal Comparison within TV Words DataFrame
    for idx1, idx2 in product(tv_words.index, repeat=2):
        if idx1 != idx2:
            topic1_words = set(tv_words.loc[idx1, 'Representation'])
            topic2_words = set(tv_words.loc[idx2, 'Representation'])
            jaccard_score = len(topic1_words.intersection(topic2_words)) / len(topic1_words.union(topic2_words))
            result.append({'Source1': 'TV', 'Topic1': idx1-1, 'Source2': 'TV', 'Topic2': idx2-1, 'Similarity': jaccard_score})

    # Cross-Dataframe Comparison between Email and Podcast Words DataFrames
    for idx1, idx2 in product(email_words.index, podcast_words.index):
        topic1_words = set(email_words.loc[idx1, 'Representation'])
        topic2_words = set(podcast_words.loc[idx2, 'Representation'])
        jaccard_score = len(topic1_words.intersection(topic2_words)) / len(topic1_words.union(topic2_words))
        result.append({'Source1': 'Email', 'Topic1': idx1-1, 'Source2': 'Podcast', 'Topic2': idx2-1, 'Similarity': jaccard_score})

    # Cross-Dataframe Comparison between Email and TV Words DataFrames
    for idx1, idx2 in product(email_words.index, tv_words.index):
        topic1_words = set(email_words.loc[idx1, 'Representation'])
        topic2_words = set(tv_words.loc[idx2, 'Representation'])
        jaccard_score = len(topic1_words.intersection(topic2_words)) / len(topic1_words.union(topic2_words))
        result.append({'Source1': 'Email', 'Topic1': idx1-1, 'Source2': 'TV', 'Topic2': idx2-1, 'Similarity': jaccard_score})

    # Cross-Dataframe Comparison between Podcast and TV Words DataFrames
    for idx1, idx2 in product(podcast_words.index, tv_words.index):
        topic1_words = set(podcast_words.loc[idx1, 'Representation'])
        topic2_words = set(tv_words.loc[idx2, 'Representation'])
        jaccard_score = len(topic1_words.intersection(topic2_words)) / len(topic1_words.union(topic2_words))
        result.append({'Source1': 'Podcast', 'Topic1': idx1-1, 'Source2': 'TV', 'Topic2': idx2-1, 'Similarity': jaccard_score})

    # Create a dataframe from the results
    similarity_df = pd.DataFrame(result)
    return similarity_df

In [9]:
similarity_results = calculate_jaccard_similarity(email_words, podcast_words, tv_words)

In [10]:
sorted_similarities = similarity_results.sort_values(by='Similarity', ascending=False)
sorted_similarities = sorted_similarities[sorted_similarities['Similarity'] != 0]
sorted_similarities

       Source1  Topic1 Source2  Topic2  Similarity
18949    Email     114   Email     140    1.000000
23214    Email     140   Email     114    1.000000
17423    Email     105   Email      98    0.818182
25340    Email     153   Email      95    0.818182
15827    Email      95   Email     153    0.818182
...        ...     ...     ...     ...         ...
120568      TV     235      TV      51    0.025641
120583      TV     235      TV      66    0.025641
120550      TV     235      TV      33    0.025641
120553      TV     235      TV      36    0.025641
120526      TV     235      TV       9    0.025641

[41788 rows x 5 columns]

In [11]:
filtered_results = sorted_similarities[(sorted_similarities['Source1'] != sorted_similarities['Source2'])]

In [12]:
filtered_results = filtered_results[(filtered_results['Similarity'] >= 0.4) & 
                                    ((filtered_results['Topic1'] != 0) & (filtered_results['Topic2'] != 0))]

In [13]:
filtered_results.shape

(47, 5)

In [14]:
filtered_results

        Source1  Topic1  Source2  Topic2  Similarity
230380  Podcast      25       TV      72    0.500000
223972  Podcast       5       TV      24    0.500000
227145  Podcast      15       TV      17    0.500000
224298  Podcast       6       TV      32    0.500000
231907  Podcast      30       TV       9    0.500000
147735    Email       6  Podcast      85    0.428571
225940  Podcast      11       TV      84    0.428571
246912  Podcast      77       TV      68    0.428571
147651    Email       6  Podcast       1    0.428571
147653    Email       6  Podcast       3    0.428571
240592  Podcast      57       TV     108    0.428571
147707    Email       6  Podcast      57    0.428571
225875  Podcast      11       TV      19    0.428571
169894    Email       1       TV       6    0.428571
147661    Email       6  Podcast      11    0.428571
147656    Email       6  Podcast       6    0.428571
147654    Email       6  Podcast       4    0.428571
147727    Email       6  Podcast      77    0.428571
240503  Podcast      57       TV      19    0.428571
147720    Email       6  Podcast      70    0.428571
240620  Podcast      57       TV     136    0.428571
257131  Podcast     109       TV     111    0.428571
222698  Podcast       1       TV      22    0.428571
257121  Podcast     109       TV     101    0.428571
239893  Podcast      55       TV      45    0.428571
225964  Podcast      11       TV     108    0.428571
257088  Podcast     109       TV      68    0.428571
257163  Podcast     109       TV     143    0.428571
225992  Podcast      11       TV     136    0.428571
222830  Podcast       1       TV     154    0.428571
240636  Podcast      57       TV     152    0.428571
246863  Podcast      77       TV      19    0.428571
226008  Podcast      11       TV     152    0.428571
230971  Podcast      27       TV      27    0.428571
257108  Podcast     109       TV      88    0.428571
174986    Email      17       TV      10    0.428571
247056  Podcast      77       TV     212    0.428571
247113  Podcast      77       TV     269    0.428571
246980  Podcast      77       TV     136    0.428571
246952  Podcast      77       TV     108    0.428571
246955  Podcast      77       TV     111    0.428571
246959  Podcast      77       TV     115    0.428571
246982  Podcast      77       TV     138    0.428571
246987  Podcast      77       TV     143    0.428571
173400    Email      12       TV      14    0.428571
246996  Podcast      77       TV     152    0.428571
181359    Email      37       TV      23    0.428571

In [15]:
email_cluster[email_cluster['Topic']==61]

,Topic,Count,Name,Representation,Representative_Docs
62,61,375,61_king_john king_follow on_john,"[king, john king, follow on, john, king for, j...","[JohnPaid for by John King for Governor, Eliza..."

In [16]:
podcast_cluster[podcast_cluster['Topic']==25]

,Topic,Count,Name,Representation,Representative_Docs
26,25,812,25_oz_fetterman_dr oz_dr,"[oz, fetterman, dr oz, dr, he, hes, pennsylvan...","[I really, the coif is very important to my se..."

In [17]:
tv_clusters[tv_clusters['Topic']==72]

,Topic,Count,Name,Representation,Representative_Docs
73,72,3242,72_fetterman_oz_john fetterman_pennsylvania,"[fetterman, oz, john fetterman, pennsylvania, ...","[>> we saw the president, another joe, was in ..."

In [18]:
link_pod_em = pd.read_pickle('/scratch/rm1667/rm1667-outputs/Podcast/podcast-email-passage-sim.pkl')
link_pod_em

,Pod_Pass,Pod_Ids,Em_Pass,Em_Ids,Scores
0,And welcome back fellow American patriots and ...,0,LindseyGraham.com The Left supports legislatio...,62003,0.729178
1,It's about auditing all of the policies that o...,1,"**Pre-existing conditions, life-threatening di...",237928,0.621318
2,"Certainly behind the food supply, buying up al...",2,And that’s exactlywhat happened. This is actua...,202484,0.545094
3,This is chemical warfare brought to you by Chi...,3,There is a fatal overdose epidemic in our Comm...,224900,0.525822
4,That's what we used to fight for. Now your abi...,4,"Peter, Gas prices are through the roof, but Jo...",144446,0.633492
...,...,...,...,...,...
656035,"I mean, it's science. I mean, what, is that no...",656035,Will be increased 700% ...,240176,0.410951
656036,And he was kind of waterboarding himself with ...,656036,He earned an appointment to the UnitedStates M...,212223,0.489725
656037,Spokane sounds way cooler. Yeah. What are we g...,656037,"Peter, This Sunday, I’ll be in Spokane debatin...",19807,0.507364
656038,"But YouTube, we're about to go play hipster ho...",656038,Join me as I discuss this week's top issues D...,313703,0.439185
656039,Call me Ed Norton because I will be your medio...,656039,Elder for America PAC YouTube is censoring me....,34494,0.410979

In [37]:
link_pod_em[link_pod_em['Scores']>=0.8]

,Pod_Pass,Pod_Ids,Em_Pass,Em_Ids,Scores
5540,So there's one other point I want to make on F...,5540,"That’swhy it’s up to us to double down , capit...",274266,0.802239
8866,So this is truly disgusting that this is still...,8866,>>>**_**STOP VACCINE MANDATES NOW:****PITCH IN...,334769,0.818556
15448,Florida didn't even have a trigger law to auto...,15448,"Eric Lynn for Congress[ Hi friend, In case you...",151036,0.826111
15881,Why should they be able to insist you get a va...,15881,Any person who would like toreceive a vaccine ...,277540,0.801795
17832,And there's nothing really unique about July 4...,17832,Wiley and the team want to wish you a very Hap...,161464,0.814592
...,...,...,...,...,...
648506,"What happens with Roe v. Wade, a lot of people...",648506,"Peter, The Supreme Court just overturned Roe v...",173240,0.837130
652355,"Where sometimes I have to go back and go, wait...",652355,"Peter, The Supreme Court just overturned Roe v...",173240,0.809637
653512,"Since the start of this year alone, 2022, ther...",653512,"Peter,This past holiday weekend there were 10 ...",238047,0.851201
653590,It's a sad day for the court and for the count...,653590,"Peter, Today is a dark day in American history...",172202,0.811699
653639,This is devastating to women across this count...,653639,Today Texas’ “Trigger Abortion Ban” law has of...,99243,0.820031

In [20]:
link_tv_em = pd.read_pickle('/scratch/rm1667/rm1667-outputs/TV/tv-email-passage-sim.pkl')
link_tv_em

,Tv_Pass,Tv_Ids,Em_Pass,Em_Ids,Scores
0,"tonight on all in. >> they know it\'s true, th...",0,NBC NEWS: Jan. 6 committee focuses on Trump's ...,181621,0.604798
1,"then, the republicans suing to disqualify madi...",1,Alex Stovall for Congress The first Black Amer...,292179,0.652344
2,we have new revelations tonight about the ex p...,2,Giuliani was one of the most vocal promoters o...,314569,0.706617
3,>> it\'s way beyond what people think. includi...,3,They’re willing to put our nationalsecurity in...,274835,0.585803
4,">> just be clear, that\'s orderly false. essen...",4,Giuliani was one of the most vocal promoters o...,314569,0.680250
...,...,...,...,...,...
3987712,"michelle got the rest stylish, equal, was told...",3987712,** Michelle’s story is one that connects with ...,4013,0.436205
3987713,"don't miss your so yes, the community, the quo...",3987713,"Hi, friend – are you free to chat. As a pastor...",92381,0.442191
3987714,i'm not major dealing with stacy that i am a t...,3987714,"If we’regoing to get the truth out, we’re coun...",82139,0.513330
3987715,"ah ah, a show you do most from who are so for ...",3987715,"[ Hello, Russia has invaded the sovereignnatio...",286370,0.609266
3987716,he's a new sure with our human at the washer t...,3987716,"Hiiiiiiiiii, it’s Sammie and Dexter here, the ...",63453,0.378889

In [24]:
link_tv_em[link_tv_em['Scores']>=0.8]

,Tv_Pass,Tv_Ids,Em_Pass,Em_Ids,Scores
1846,"and the other 2 go a look, they're getting awa...",1846,"However, over the last 20years, the price of i...",247983,0.827033
2397,one mother spoke up saying that she was happy ...,2397,FIRST Glenn Youngkin violated the Virginia Con...,319546,0.814787
5436,"joe biden, us funding self squabbling with ame...",5436,"96 Peter, Joe Biden’s presidency hasbeen a dis...",321044,0.806137
7686,>> in some ways it\'s weird how oz has made th...,7686,**Send John Fetterman your support so we can k...,76715,0.811167
7720,">> i prefer a kansas that has fewer abortions,...",7720,The people of Kansas will speak directly to th...,172306,0.818544
...,...,...,...,...,...
3984872,[applause] >> tonight we are also keeping a cl...,3984872,Unsubscribe IN CASE YOUMISSED IT: PRESIDENT TR...,243409,0.805166
3984933,"despite the colossal understatement of a name,...",3984933,"In addition to tackling inflation, the bill ad...",117189,0.814615
3987264,energy prices are up even more. gas prices are...,3987264,Joe Biden's war on American Energy is fueling ...,215905,0.806295
3987267,take another look at your screen. gas prices r...,3987267,Skyrocketing GasPrices: While closely intertwi...,266142,0.812782
3987279,joe biden clearly is a cognitive wreck and we ...,3987279,"Peter, I can’t believe it. Joe Biden said that...",200792,0.809439

In [22]:
link_tv_pod = pd.read_pickle('/scratch/rm1667/rm1667-outputs/TV/tv-podcast-passage-sim.pkl')
link_tv_pod

,Tv_Pass,Tv_Ids,Pod_Pass,Pod_Ids,Scores
0,"tonight on all in. >> they know it\'s true, th...",0,"And that's the deep state. Remember, we talked...",537622,0.603253
1,"then, the republicans suing to disqualify madi...",1,"So that's nice progress. Yeah, this has been L...",650427,0.608871
2,we have new revelations tonight about the ex p...,2,And all the stuff raised initially by Giuliani...,593789,0.717742
3,>> it\'s way beyond what people think. includi...,3,That's that's a quote from the FBI guy that ca...,452261,0.564830
4,">> just be clear, that\'s orderly false. essen...",4,And all the stuff raised initially by Giuliani...,593789,0.690533
...,...,...,...,...,...
3987712,"michelle got the rest stylish, equal, was told...",3987712,And I'm just going to take a little tour on th...,124255,0.486387
3987713,"don't miss your so yes, the community, the quo...",3987713,"Welcome to the JBP Podcast, Season 4, Episode ...",572003,0.470098
3987714,i'm not major dealing with stacy that i am a t...,3987714,"But the fact that there was a petition, okay, ...",213111,0.539645
3987715,"ah ah, a show you do most from who are so for ...",3987715,"But we're not even trying. No, we're not even ...",385045,0.683280
3987716,he's a new sure with our human at the washer t...,3987716,"I mean, no way you're thinking, man, what I ne...",236052,0.483709

In [28]:
link_tv_pod[link_tv_pod['Scores']>=0.9]

,Tv_Pass,Tv_Ids,Pod_Pass,Pod_Ids,Scores
11421,"you know, what happened with me and trump, lar...",11421,"You know, what happened with me and Trump, Lar...",282385,0.944596
11471,we intend to hold anyone -- anyone who is crim...,11471,"We intend to hold everyone, anyone who was cri...",506681,0.957981
22367,"as things stand, if this means that you miss t...",22367,"Ultimately, are you prepared to forego the cha...",504662,0.982938
23387,as long as there is hope of diplomaticresoluti...,23387,As long as there is hope of diplomatic resolut...,539839,0.991469
40560,except for one former american president who t...,40560,Why did the mayor of Moscow's wife give the Bi...,257345,0.909663
...,...,...,...,...,...
3985491,we wanted to make sure there was plenty of nat...,3985491,We wanted to make sure that there was plenty o...,530636,0.960518
3986472,"and i\'ve a question for you, you are running ...",3986472,And I have a question for you. You're running ...,648129,0.963108
3986875,>> are you in fact in favor of gun confiscatio...,3986875,"Listen, Americans will who own a R-15s, AK-47s...",551553,0.906796
3986949,so the idea is maybe like the covington cathol...,3986949,"So the idea is, maybe like the Covington Catho...",342566,0.915486
3987567,"i'll tell you exactly what happens, tim. what ...",3987567,"I'll tell you exactly what happens, Tim. What ...",604504,0.987612